name: Update Profile Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get GitHub stats via GraphQL
        id: stats
        run: |
          python3 << 'EOF'
          import os
          import requests
          import json
          from datetime import datetime, timedelta
          
          GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
          USERNAME = 'j-vaught'
          
          # GraphQL query for comprehensive stats
          graphql_url = 'https://api.github.com/graphql'
          headers = {
              'Authorization': f'Bearer {GITHUB_TOKEN}',
              'Content-Type': 'application/json'
          }
          
          # Get user contributions with commit data
          query = '''
          query($login: String!) {
            user(login: $login) {
              repositories(first: 100, ownerAffiliations: OWNER, orderBy: {field: UPDATED_AT, direction: DESC}) {
                nodes {
                  name
                  language
                  defaultBranchRef {
                    target {
                      ... on Commit {
                        history(first: 1) {
                          nodes {
                            additions
                            deletions
                          }
                        }
                      }
                    }
                  }
                }
              }
              contributionsCollection {
                totalCommitContributions
                totalPullRequestContributions
                totalIssueContributions
              }
            }
          }
          '''
          
          response = requests.post(graphql_url, json={'query': query, 'variables': {'login': USERNAME}}, headers=headers)
          data = response.json()
          
          if 'errors' in data:
              print(f"GraphQL errors: {data['errors']}")
          
          user_data = data.get('data', {}).get('user', {})
          repos = user_data.get('repositories', {}).get('nodes', [])
          contributions = user_data.get('contributionsCollection', {})
          
          # Calculate stats
          total_commits = contributions.get('totalCommitContributions', 0)
          total_prs = contributions.get('totalPullRequestContributions', 0)
          total_issues = contributions.get('totalIssueContributions', 0)
          
          # Language breakdown
          languages = {}
          for repo in repos:
              lang = repo.get('language')
              if lang:
                  languages[lang] = languages.get(lang, 0) + 1
          
          sorted_langs = sorted(languages.items(), key=lambda x: x[1], reverse=True)
          total_repos = len([r for r in repos if r.get('language')])
          
          lang_badge = "| Language | Repos | % |\n|:---|:---:|---:|\n"
          for lang, count in sorted_langs[:10]:
              pct = (count / total_repos * 100) if total_repos > 0 else 0
              lang_badge += f"| {lang} | {count} | {pct:.1f}% |\n"
          
          # Output
          with open('stats.json', 'w') as f:
              json.dump({
                  'total_commits': total_commits,
                  'total_prs': total_prs,
                  'total_issues': total_issues,
                  'repo_count': len(repos),
                  'languages': lang_badge
              }, f)
          
          print(f"Commits: {total_commits}, PRs: {total_prs}, Issues: {total_issues}")
          print(f"Repos: {len(repos)}, Languages: {len(sorted_langs)}")
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          python3 << 'EOF'
          import re
          import json
          
          with open('stats.json', 'r') as f:
              stats = json.load(f)
          
          with open('profile/README.md', 'r') as f:
              content = f.read()
          
          content = re.sub(r'<!-- repo-count -->', str(stats['repo_count']), content)
          
          pattern = r'<!-- languages-breakdown-start -->.*<!-- languages-breakdown-end -->'
          content = re.sub(pattern, f'<!-- languages-breakdown-start -->\n\n{stats["languages"]}\n<!-- languages-breakdown-end -->', content, flags=re.DOTALL)
          
          with open('profile/README.md', 'w') as f:
              f.write(content)
          EOF

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add profile/README.md
          git diff --quiet || git commit -m "Update profile stats"
          git push

  update_activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Updated recent activity"
          MAX_LINES: 10

      - name: Commit activity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add profile/README.md
          git diff --quiet || git commit -m "Update recent activity" || true
          git push || true
