name: Update Profile

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get user stats
        id: stats
        run: |
          REPO_COUNT=$(gh api users/j-vaught --jq '.public_repos')
          echo "repo_count=$REPO_COUNT" >> $GITHUB_OUTPUT

      - name: Update README with repo count
        run: |
          sed -i 's/<!-- repo-count -->/${{ steps.stats.outputs.repo_count }}/' profile/README.md

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add profile/README.md
          git diff --quiet || git commit -m "Update profile stats"
          git push

  update_activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Updated recent activity"
          MAX_LINES: 10

      - name: Commit activity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add profile/README.md
          git diff --quiet || git commit -m "Update recent activity" || true
          git push || true
